import "../globals.css";
  
export const metadata = {
  title: "Jainik contact layout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning> contact Page layout file {children}</body>
    </html>
  );
}
